services:
  - type: web
    name: inbox-recovery-backend
    runtime: node
    repo: https://github.com/nicolasferoli/recoverymail
    branch: main
    rootDir: backend
    buildCommand: npm ci && npm run build:force
    startCommand: npm run start:all
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: API_URL
        value: https://api.inboxrecovery.com
    healthCheckPath: /health
    autoDeploy: true 