services:
  - type: web
    name: inbox-recovery-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000 